dist: bionic
sudo: required
language:
  - c++
compiler:
  - gcc
addons:
  apt:
    update: true
    packages:
      - cmake
      - libc6-i386
install:
  - wget https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q3-update/+download/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2
  - sudo tar -xf gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2 -C /opt

script:
  - mkdir build && pushd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain.cmake  -DCROSS_COMPILE=/opt/gcc-arm-none-eabi-5_4-2016q3/bin/arm-none-eabi- -DCMAKE_BUILD_TYPE=Release ..
  - make -j2
